import type { BuilderHomepageConfig, BuilderSiteConfig } from "@/lib/types/builder";

/**
 * Demo / mock homepage builder payloads. Replace with Firestore/CMS reads later.
 * Media URLs are external only — do not vendor binaries into the repo.
 * Official: workspace / SaaS / platform mood. Tenant: repair shop / accessories / trust (no code-screen imagery).
 */

const PX = "auto=compress&cs=tinysrgb";

const OFFICIAL_SLIDES = [
    {
        id: "official-slide-1",
        title: "Multi-tenant SaaS 骨架",
        description: "租戶隔離、角色邊界與營運資料一致，讓模組在穩固地基上疊加。",
        buttonText: "平台定位",
        buttonHref: "#platform",
        desktopImageUrl: `https://images.pexels.com/photos/3184292/pexels-photo-3184292.jpeg?${PX}&w=1920`,
        mobileImageUrl: `https://images.pexels.com/photos/3184292/pexels-photo-3184292.jpeg?${PX}&w=960`,
        overlayEnabled: true,
        overlayStrength: 0.4,
        isActive: true,
        openInNewTab: false,
        startAt: null,
        endAt: null,
    },
    {
        id: "official-slide-2",
        title: "ERP · Repair · POS · Commerce",
        description: "案件、庫存、櫃台與展示頁維持同一條營運鏈路，而不是四套分散工具。",
        buttonText: "模組總覽",
        buttonHref: "#modules",
        desktopImageUrl: `https://images.pexels.com/photos/265087/pexels-photo-265087.jpeg?${PX}&w=1920`,
        mobileImageUrl: `https://images.pexels.com/photos/265087/pexels-photo-265087.jpeg?${PX}&w=960`,
        overlayEnabled: true,
        overlayStrength: 0.38,
        isActive: true,
        openInNewTab: false,
        startAt: null,
        endAt: null,
    },
    {
        id: "official-slide-3",
        title: "AI 營運層預留",
        description: "助理、知識檢索與流程建議與既有資料模型對齊，方便後續接軌。",
        buttonText: "Roadmap",
        buttonHref: "#progress",
        desktopImageUrl: `https://images.pexels.com/photos/6476589/pexels-photo-6476589.jpeg?${PX}&w=1920`,
        mobileImageUrl: `https://images.pexels.com/photos/6476589/pexels-photo-6476589.jpeg?${PX}&w=960`,
        overlayEnabled: true,
        overlayStrength: 0.4,
        isActive: true,
        openInNewTab: false,
        startAt: null,
        endAt: null,
    },
    {
        id: "official-slide-4",
        title: "提案 · 作品集 · 商業化敘事",
        description: "同一套首頁可對外展示產品故事、履歷作品與 PoC／導入討論入口。",
        buttonText: "Demo 帳號",
        buttonHref: "#demo",
        desktopImageUrl: `https://images.pexels.com/photos/8386442/pexels-photo-8386442.jpeg?${PX}&w=1920`,
        mobileImageUrl: `https://images.pexels.com/photos/8386442/pexels-photo-8386442.jpeg?${PX}&w=960`,
        overlayEnabled: true,
        overlayStrength: 0.39,
        isActive: true,
        openInNewTab: false,
        startAt: null,
        endAt: null,
    },
] as const;

const TENANT_SLIDES = [
    {
        id: "tenant-slide-1",
        title: "現場檢測 · 透明報價",
        description: "檢測過程與估價說清楚，減少爭議、建立信任。",
        buttonText: "服務項目",
        buttonHref: "#services",
        desktopImageUrl: `https://images.pexels.com/photos/3861969/pexels-photo-3861969.jpeg?${PX}&w=1920`,
        mobileImageUrl: `https://images.pexels.com/photos/3861969/pexels-photo-3861969.jpeg?${PX}&w=960`,
        overlayEnabled: true,
        overlayStrength: 0.46,
        isActive: true,
        openInNewTab: false,
        startAt: null,
        endAt: null,
    },
    {
        id: "tenant-slide-2",
        title: "螢幕 · 電池 · 充電埠",
        description: "常見料件與工時可視覺化呈現，讓客戶快速理解方案。",
        buttonText: "立即預約",
        buttonHref: "#contact",
        desktopImageUrl: `https://images.pexels.com/photos/788946/pexels-photo-788946.jpeg?${PX}&w=1920`,
        mobileImageUrl: `https://images.pexels.com/photos/788946/pexels-photo-788946.jpeg?${PX}&w=960`,
        overlayEnabled: true,
        overlayStrength: 0.44,
        isActive: true,
        openInNewTab: false,
        startAt: null,
        endAt: null,
    },
    {
        id: "tenant-slide-3",
        title: "高品質保護貼 · 手機殼 · 配件",
        description: "精選保護與周邊，提升手感與耐用度，門市可搭配方案推薦。",
        buttonText: "查看配件",
        buttonHref: "#services",
        desktopImageUrl: `https://images.pexels.com/photos/5716002/pexels-photo-5716002.jpeg?${PX}&w=1920`,
        mobileImageUrl: `https://images.pexels.com/photos/5716002/pexels-photo-5716002.jpeg?${PX}&w=960`,
        overlayEnabled: true,
        overlayStrength: 0.43,
        isActive: true,
        openInNewTab: false,
        startAt: null,
        endAt: null,
    },
    {
        id: "tenant-slide-4",
        title: "二手機 · 舊機回收 · 升級方案",
        description: "估價與回收流程可與門市政策對齊，讓升級換機更順。",
        buttonText: "聯絡門市",
        buttonHref: "#contact",
        desktopImageUrl: `https://images.pexels.com/photos/3783579/pexels-photo-3783579.jpeg?${PX}&w=1920`,
        mobileImageUrl: `https://images.pexels.com/photos/3783579/pexels-photo-3783579.jpeg?${PX}&w=960`,
        overlayEnabled: true,
        overlayStrength: 0.45,
        isActive: true,
        openInNewTab: false,
        startAt: null,
        endAt: null,
    },
] as const;

export const OFFICIAL_BUILDER_HOMEPAGE_CONFIG: BuilderHomepageConfig = {
    siteType: "official",
    themeVariant: "official",
    sectionOrder: ["hero", "carousel", "platform"],
    sectionsEnabled: {
        hero: true,
        carousel: true,
    },
    hero: {
        enabled: true,
        backgroundType: "video",
        height: "screen",
        contentAlign: "left",
        textAlign: "left",
        contentPanelSize: "sm",
        overlayStrength: 0.34,
        videoUrl: "https://videos.pexels.com/video-files/2495380/2495380-hd_1920_1080_30fps.mp4",
        posterUrl: `https://images.pexels.com/photos/1181396/pexels-photo-1181396.jpeg?${PX}&w=1920`,
        eyebrow: "Ticket Core · SaaS + AI",
        title: "多租戶 ERP + Repair + POS + Commerce 核心平台",
        description: "以可商業化的產品節奏呈現：提案、作品集與實機流程在同一條敘事線上。",
        primaryAction: { label: "查看平台定位", href: "#platform", variant: "primary", openInNewTab: false },
        secondaryAction: { label: "測試帳號與 Demo", href: "#demo", variant: "secondary", openInNewTab: false },
    },
    carousel: {
        enabled: true,
        autoplay: true,
        intervalMs: 6200,
        showArrows: true,
        showDots: true,
        pauseOnHover: true,
        slides: [...OFFICIAL_SLIDES],
    },
};

export const TENANT_BUILDER_HOMEPAGE_CONFIG: BuilderHomepageConfig = {
    siteType: "tenant",
    themeVariant: "neutral",
    sectionOrder: ["hero", "carousel", "legacy-blocks"],
    sectionsEnabled: {
        hero: true,
        carousel: true,
    },
    hero: {
        enabled: true,
        backgroundType: "video",
        height: "tall",
        contentAlign: "center",
        textAlign: "center",
        contentPanelSize: "md",
        overlayStrength: 0.4,
        videoUrl: "https://videos.pexels.com/video-files/6853335/6853335-hd_1920_1080_25fps.mp4",
        posterUrl: `https://images.pexels.com/photos/7514838/pexels-photo-7514838.jpeg?${PX}&w=1920`,
        eyebrow: "手機維修 · 高品質配件",
        title: "快速檢測 · 透明報價 · 門市安心服務",
        description: "專注手機維修與精選配件：現場溝通清楚、工時與料件可追溯，讓客戶放心把手機交給我們。",
        primaryAction: { label: "服務項目", href: "#services", variant: "primary", openInNewTab: false },
        secondaryAction: { label: "聯絡我們", href: "#contact", variant: "secondary", openInNewTab: false },
    },
    carousel: {
        enabled: true,
        autoplay: true,
        intervalMs: 5800,
        showArrows: true,
        showDots: true,
        pauseOnHover: true,
        slides: [...TENANT_SLIDES],
    },
};

export const BUILDER_SITE_CONFIG_DEMO: BuilderSiteConfig = {
    officialSite: OFFICIAL_BUILDER_HOMEPAGE_CONFIG,
    tenantSite: TENANT_BUILDER_HOMEPAGE_CONFIG,
};
