import { cookies, headers } from "next/headers";
import { MerchantPageShell } from "@/components/merchant/shell";
import { ShowcaseBuilder } from "@/features/showcase/components/ShowcaseBuilder";
import { getShowcasePreferences } from "@/features/showcase/services/showcasePreferences.server";
import { getLocaleFromHeader } from "@/lib/i18n/authIndex";
import { getCurrentSessionAccountContext } from "@/lib/services/staff.service";

export default async function ShowcaseBuilderPage() {
    const h = await headers();
    const c = await cookies();
    const langCookie = c.get("lang")?.value;
    const locale = langCookie === "en" ? "en" : getLocaleFromHeader(h.get("accept-language"));
    const accountContext = await getCurrentSessionAccountContext();
    const tenantId = accountContext?.tenantId ?? null;
    const preferences = await getShowcasePreferences({ tenantId });

    const labels =
        locale === "en"
            ? {
                  title: "Showcase Builder",
                  hint: "Gutenberg-inspired builder with block list, live canvas, and inspector controls.",
                  save: "Save Changes",
                  saving: "Saving...",
                  saved: "Saved",
                  saveFailed: "Save failed",
                  saveFailedWithReason: "Save failed",
                  resetAll: "Reset All",
                  resetBlock: "Reset Block",
                  resetTheme: "Reset Theme",
                  localeZh: "ZH",
                  localeEn: "EN",
                  audienceLabel: "Preview Audience",
                  audienceGuest: "Guest",
                  audienceCompany: "Company",
                  audienceCustomer: "Customer",
                  viewportLabel: "Viewport",
                  viewportDesktop: "Desktop",
                  viewportMobile: "Mobile",
                  usingDefaultTemplate: "Using default template fallback",
                  orderHint: "Reorder sections here. Current schema is ready for drag sorting and future insertion flow.",
                  dragHint: "Drag a block card or use move controls to change layout order.",
                  enabled: "Enabled",
                  hidden: "Hidden",
                  moveUp: "Move Up",
                  moveDown: "Move Down",
                  sectionListTitle: "Blocks",
                  previewTitle: "Canvas",
                  inspectorTitle: "Inspector",
                  libraryTitle: "Inserter",
                  libraryHint: "Current company-home template keeps one instance per block type. UI is ready for future block insertion expansion.",
                  libraryInUse: "In layout",
                  libraryFixed: "Template slot",
                  fieldAnchor: "Anchor",
                  fieldKicker: "Kicker",
                  fieldTitle: "Title",
                  fieldBody: "Body Text",
                  fieldHeroSummaryTitle: "Hero Summary Title",
                  fieldContactCardTitle: "Contact Card Title",
                  fieldContactCardBody: "Contact Card Body",
                  fieldPoints: "List Content",
                  pointsHint: "One line per item",
                  fieldFontFamily: "Font Family",
                  fieldTitleScale: "Title Size",
                  fieldBodyScale: "Body Size",
                  fieldServiceCards: "Service Cards",
                  fieldServiceRows: "Rows",
                  fieldServiceCardTitle: "Card Title",
                  fieldServiceCardBody: "Card Body",
                  fieldServiceCardImage: "Card Image",
                  fieldServiceCardImageUrl: "Image URL",
                  fieldServiceCardImageSourceType: "Image Source",
                  fieldServiceCardStoragePath: "Storage Path",
                  fieldServiceCardImageStyle: "Image Shape",
                  fieldServiceCardImagePosition: "Image Position",
                  fieldServiceCardShowImage: "Show Image",
                  fieldServiceCardShowTitle: "Show Title",
                  fieldServiceCardShowBody: "Show Body",
                  uploadImage: "Upload Image",
                  confirmUploadImage: "Confirm Upload",
                  selectedImage: "Selected File",
                  imageUploadSuccess: "Image uploaded. Click Save to persist.",
                  uploadingImage: "Uploading image...",
                  clearImage: "Clear Image",
                  imageUploadFailed: "Image upload failed",
                  optionImageSquare: "Square",
                  optionImageCircle: "Circle",
                  optionImageTop: "Top",
                  optionImageBottom: "Bottom",
                  optionImageLeft: "Left",
                  optionImageRight: "Right",
                  optionImageSourceExternal: "External URL",
                  optionImageSourceStorage: "Storage File",
                  optionServiceRows1: "1 row (3 cards)",
                  optionServiceRows2: "2 rows (6 cards)",
                  optionServiceRows3: "3 rows (9 cards)",
                  optionFontDefault: "Default",
                  optionFontSerif: "Serif",
                  optionFontMono: "Monospace",
                  optionTitleMd: "Medium",
                  optionTitleLg: "Large",
                  optionTitleXl: "XL",
                  optionBodySm: "Small",
                  optionBodyMd: "Medium",
                  optionBodyLg: "Large",
                  styleSectionTitle: "Block Styles",
                  styleBackgroundColor: "Background Color",
                  styleTextColor: "Text Color",
                  styleAccentColor: "Accent Color",
                  styleBorderColor: "Border Color",
                  styleMutedColor: "Muted Text Color",
                  styleSurfaceColor: "Surface Color",
                  styleCardBackgroundColor: "Card Background",
                  styleSummaryBackgroundColor: "Summary Background",
                  styleBorderRadius: "Border Radius",
                  stylePadding: "Padding",
                  styleAlign: "Text Alignment",
                  optionAlignLeft: "Left",
                  optionAlignCenter: "Center",
                  optionAlignRight: "Right",
                  typographySectionTitle: "Typography Colors",
                  typographyKickerColor: "Kicker Color",
                  typographyTitleColor: "Title Color",
                  typographyBodyColor: "Body Color",
                  ctaSectionTitle: "CTA Settings",
                  ctaLabel: "CTA Label",
                  ctaHref: "CTA Link",
                  ctaVariant: "CTA Style",
                  ctaOpenInNewTab: "Open In New Tab",
                  optionCtaSolid: "Solid",
                  optionCtaOutline: "Outline",
                  optionCtaGhost: "Ghost",
                  themeOverrideSectionTitle: "Theme Token Overrides",
                  themeOverrideHint: "One per line, use token=value. Example: --showcase-accent=30 112 99",
                  themeOverridePlaceholder: "--showcase-accent=30 112 99",
                  themeSectionTitle: "Page Theme",
                  themeCustomColor: "Custom Color",
                  storefrontTitle: "Storefront Settings",
                  storefrontHint: "Control online shopping availability and customer navigation behavior.",
                  storefrontShoppingEnabled: "Enable Online Shopping",
                  storefrontAutoRedirect: "Auto redirect customer to shop after login",
                  storefrontShowCart: "Show cart icon in homepage nav",
                  schemaSectionTitle: "Block JSON Snapshot",
                  schemaHint: "Read-only snapshot of the active block schema for migration-safe inspection.",
                  rolePage: "Page Background",
                  roleHeader: "Header Background",
                  roleHero: "Hero Background",
                  roleAbout: "About Background",
                  roleServices: "Services Background",
                  roleContact: "Contact Background",
                  roleAd: "Ad Background",
                  roleFooter: "Footer Background",
                  roleShopPage: "Shop Page Background",
                  roleShopHeader: "Shop Header Background",
                  roleShopHero: "Shop Hero Background",
                  roleShopGrid: "Shop Grid Background",
                  roleShopFooter: "Shop Footer Background",
                  blockHero: "Hero",
                  blockAbout: "About",
                  blockServices: "Services",
                  blockContact: "Contact",
                  blockAd: "Ad Banner",
              }
            : {
                  title: "展示頁 Builder",
                  hint: "Gutenberg 風格單頁 builder：左側區塊列表、中間即時預覽、右側 inspector。",
                  save: "儲存修改",
                  saving: "儲存中...",
                  saved: "已儲存",
                  saveFailed: "儲存失敗",
                  saveFailedWithReason: "儲存失敗",
                  resetAll: "全部重設",
                  resetBlock: "重設目前區塊",
                  resetTheme: "重設主題",
                  localeZh: "中",
                  localeEn: "EN",
                  audienceLabel: "預覽身份",
                  audienceGuest: "訪客",
                  audienceCompany: "公司",
                  audienceCustomer: "客戶",
                  viewportLabel: "預覽尺寸",
                  viewportDesktop: "桌機",
                  viewportMobile: "手機",
                  usingDefaultTemplate: "目前使用 default template fallback",
                  orderHint: "在這裡調整區塊順序；目前 schema 已預留拖曳排序與未來插入器流程。",
                  dragHint: "可直接拖曳區塊卡片，或用上下移動按鈕調整版面順序。",
                  enabled: "啟用",
                  hidden: "隱藏",
                  moveUp: "往上",
                  moveDown: "往下",
                  sectionListTitle: "區塊列表",
                  previewTitle: "即時預覽",
                  inspectorTitle: "Inspector",
                  libraryTitle: "插入器",
                  libraryHint: "目前 company-home 模板維持每種 block type 各一個實例，UI 已預留後續擴充插入器。",
                  libraryInUse: "已在版面",
                  libraryFixed: "模板區塊",
                  fieldAnchor: "Anchor",
                  fieldKicker: "區塊前綴文字",
                  fieldTitle: "主標題",
                  fieldBody: "內文",
                  fieldHeroSummaryTitle: "Hero 摘要標題",
                  fieldContactCardTitle: "聯絡卡片標題",
                  fieldContactCardBody: "聯絡卡片內容",
                  fieldPoints: "列表內容",
                  pointsHint: "一行代表一筆",
                  fieldFontFamily: "字體樣式",
                  fieldTitleScale: "標題尺寸",
                  fieldBodyScale: "內文字級",
                  fieldServiceCards: "服務卡片",
                  fieldServiceRows: "顯示列數",
                  fieldServiceCardTitle: "卡片標題",
                  fieldServiceCardBody: "卡片內容",
                  fieldServiceCardImage: "卡片圖片",
                  fieldServiceCardImageUrl: "圖片 URL",
                  fieldServiceCardImageSourceType: "圖片來源",
                  fieldServiceCardStoragePath: "儲存路徑",
                  fieldServiceCardImageStyle: "圖片形狀",
                  fieldServiceCardImagePosition: "圖片位置",
                  fieldServiceCardShowImage: "顯示圖片",
                  fieldServiceCardShowTitle: "顯示標題",
                  fieldServiceCardShowBody: "顯示內容",
                  uploadImage: "上傳圖片",
                  confirmUploadImage: "確認上傳",
                  selectedImage: "已選檔案",
                  imageUploadSuccess: "圖片上傳成功，請按儲存",
                  uploadingImage: "圖片上傳中...",
                  clearImage: "清除圖片",
                  imageUploadFailed: "圖片上傳失敗",
                  optionImageSquare: "方形",
                  optionImageCircle: "圓形",
                  optionImageTop: "上方",
                  optionImageBottom: "下方",
                  optionImageLeft: "左方",
                  optionImageRight: "右方",
                  optionImageSourceExternal: "外部網址",
                  optionImageSourceStorage: "儲存檔案",
                  optionServiceRows1: "1 列（3 張）",
                  optionServiceRows2: "2 列（6 張）",
                  optionServiceRows3: "3 列（9 張）",
                  optionFontDefault: "預設",
                  optionFontSerif: "襯線字",
                  optionFontMono: "等寬字",
                  optionTitleMd: "中",
                  optionTitleLg: "大",
                  optionTitleXl: "特大",
                  optionBodySm: "小",
                  optionBodyMd: "中",
                  optionBodyLg: "大",
                  styleSectionTitle: "區塊樣式",
                  styleBackgroundColor: "背景色",
                  styleTextColor: "文字色",
                  styleAccentColor: "重點色",
                  styleBorderColor: "邊框色",
                  styleMutedColor: "次要文字色",
                  styleSurfaceColor: "表面底色",
                  styleCardBackgroundColor: "卡片背景色",
                  styleSummaryBackgroundColor: "摘要背景色",
                  styleBorderRadius: "圓角",
                  stylePadding: "內距",
                  styleAlign: "文字對齊",
                  optionAlignLeft: "左",
                  optionAlignCenter: "中",
                  optionAlignRight: "右",
                  typographySectionTitle: "字體顏色",
                  typographyKickerColor: "前綴文字色",
                  typographyTitleColor: "標題色",
                  typographyBodyColor: "內文色",
                  ctaSectionTitle: "CTA 設定",
                  ctaLabel: "按鈕文字",
                  ctaHref: "按鈕連結",
                  ctaVariant: "按鈕樣式",
                  ctaOpenInNewTab: "新分頁開啟",
                  optionCtaSolid: "實心",
                  optionCtaOutline: "外框",
                  optionCtaGhost: "文字",
                  themeOverrideSectionTitle: "Theme Token 覆蓋",
                  themeOverrideHint: "每行一筆，格式 token=value，例如：--showcase-accent=30 112 99",
                  themeOverridePlaceholder: "--showcase-accent=30 112 99",
                  themeSectionTitle: "頁面主題",
                  themeCustomColor: "自訂顏色",
                  storefrontTitle: "Storefront 設定",
                  storefrontHint: "控制是否開啟線上購物，以及客戶導覽與自動導購行為。",
                  storefrontShoppingEnabled: "開啟線上購物",
                  storefrontAutoRedirect: "客戶登入後自動導向商店頁",
                  storefrontShowCart: "首頁導覽列顯示購物車",
                  schemaSectionTitle: "Block JSON 快照",
                  schemaHint: "唯讀檢視目前區塊 schema，方便 migration-safe 盤點與除錯。",
                  rolePage: "頁面背景",
                  roleHeader: "導覽列背景",
                  roleHero: "Hero 背景",
                  roleAbout: "About 背景",
                  roleServices: "Services 背景",
                  roleContact: "Contact 背景",
                  roleAd: "廣告區塊背景",
                  roleFooter: "Footer 背景",
                  roleShopPage: "商店頁背景",
                  roleShopHeader: "商店頁導覽列背景",
                  roleShopHero: "商店頁 Hero 背景",
                  roleShopGrid: "商店頁商品區背景",
                  roleShopFooter: "商店頁 Footer 背景",
                  blockHero: "Hero 首屏",
                  blockAbout: "About 區塊",
                  blockServices: "Services 區塊",
                  blockContact: "Contact 區塊",
                  blockAd: "廣告區塊",
              };

    return (
        <MerchantPageShell
            title={labels.title}
            subtitle="以同一套作品頁 / 品牌頁設計語言編輯內容、樣式、storefront 與 schema。"
            width="builder"
        >
            <ShowcaseBuilder
                labels={labels}
                initialContent={preferences.content}
                initialThemeColors={preferences.themeColors}
                initialStorefront={preferences.storefront}
                tenantId={tenantId}
                hasSavedPreferences={preferences.updatedAt > 0}
            />
        </MerchantPageShell>
    );
}
